#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x89EFD588E975D6DF (rbtcollins@hp.com)
#
Name     : deprecated-traceback2
Version  : 1.4.0
Release  : 48
URL      : http://pypi.debian.net/traceback2/traceback2-1.4.0.tar.gz
Source0  : http://pypi.debian.net/traceback2/traceback2-1.4.0.tar.gz
Source99 : http://pypi.debian.net/traceback2/traceback2-1.4.0.tar.gz.asc
Summary  : Backports of the traceback module
Group    : Development/Tools
License  : Python-2.0
Requires: deprecated-traceback2-python = %{version}-%{release}
Requires: linecache2
BuildRequires : Babel
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : contextlib2
BuildRequires : deprecated-Babel-legacypython
BuildRequires : deprecated-pytz-legacypython
BuildRequires : deprecated-unittest2-legacypython
BuildRequires : fixtures
BuildRequires : pbr
BuildRequires : pbr-legacypython
BuildRequires : setuptools-legacypython
BuildRequires : testrepository
BuildRequires : testtools
BuildRequires : unittest2

%description
A backport of traceback to older supported Pythons.
>>> import traceback2 as traceback

%package legacypython
Summary: legacypython components for the deprecated-traceback2 package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-traceback2 package.


%package python
Summary: python components for the deprecated-traceback2 package.
Group: Default

%description python
python components for the deprecated-traceback2 package.


%prep
%setup -q -n traceback2-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554341976
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
